// Pass images drawn programmatically (pngjs): the glider mark as a solid
// dark icon tile plus transparent logo variants colored to contrast each
// category's pass background. Regenerate: scratchpad wallet/gen-images.ts
export const WALLET_ICONS: Record<string, string> = {
  "icon.png":
    "iVBORw0KGgoAAAANSUhEUgAAAB0AAAAdCAYAAABWk2cPAAAAcElEQVR4AcXBwQnEIABFwZdPChAEW7H/o60I1pC9B3MILHkzRyn14mNBEARBEARBcPLSmp272gZvBEEQBEEQBMHJH6zZ2altsBMEQRAEQXDyYM3OTm2DuzU7bwRBEARBEATBUUq9+FgQBEEQBEEQ/ADhqg2x/98F6gAAAABJRU5ErkJggg==",
  "icon@2x.png":
    "iVBORw0KGgoAAAANSUhEUgAAADoAAAA6CAYAAADhu0ooAAAAnUlEQVR4AeXBwQmEQADAwBgsQFiwFft/2sqCNXgt6EM4yMyybeMmQCIkQiIkQiIkQiIkQiIkQiJWPnTNgzfGfvIViZAIiZAIiZAIiZAIiZCIlT9yzYOnxn7yhkRIhERIhERIhERIhERIhESsvHTNg6fGfvLGNQ++IhESIRESIRESIRESIRESsWzbuAmQCImQCImQCImQCImQCImQiB8RPQ3r76HWcgAAAABJRU5ErkJggg==",
  "icon@3x.png":
    "iVBORw0KGgoAAAANSUhEUgAAAFcAAABXCAYAAABxyNlsAAAA7klEQVR4Ae3B0YkCAQDFwPiwAGHBVuz/01YWrMErQgNyZOZyux1vohjRjGhGNCOaEc2IZkQzohnRjGhGNCOaEc2IZkQzornyQ17ng08d9ye/YkQzohnRjGhGNCOaEc2IZkQzohnRjGhGNCOaEc2IZkRz5Z95nQ++4bg/+dSIZkQzohnRjGhGNCOaEc2IZkQzohnRjGhGNCOaEc2VL3idD77huD/51Ot88CtGNCOaEc2IZkQzohnRjGhGNCOaEc2IZkQzohnRjGhGNJfb7XgTxYhmRDOiGdGMaEY0I5oRzYhmRDOiGdGMaEY0I5oRzR+9lw4la3VCSwAAAABJRU5ErkJggg==",
};

export const WALLET_LOGOS: Record<string, Record<string, string>> = {
  yellow: {
    "logo.png":
      "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAVElEQVR4AbXB0QnAIBAFwb0XSHEWbHGCmArOj8DOFBd7jUPjeWfRCIIgCIIgCIIgKC72GocfgiAIgiAIgiAIaq9xaDzvLBp7jUMjCIIgCIIgCILgA6B9DqgSsAxYAAAAAElFTkSuQmCC",
    "logo@2x.png":
      "iVBORw0KGgoAAAANSUhEUgAAACoAAAAqCAYAAADFw8lbAAAAdUlEQVR4AdXBwQnEIAAAwXUDKc6CU5wgXg8+DnZmcGmvebjwvN/ggkRIhERIhERIhERIhERIhERIhEQMLu01D38kERIhERIhERIhERIhERIhERIhEWOvebjwvN/gwl7zcEEiJEIiJEIiJEIiJEIiJEIiJEIifh1vDtLr73UwAAAAAElFTkSuQmCC",
    "logo@3x.png":
      "iVBORw0KGgoAAAANSUhEUgAAAD8AAAA/CAYAAABXXxDfAAAAl0lEQVR4AeXBwQnEMADAMMeFDteBO1wg5JZIH4elwQfWfDaHXfc7OEzCJEzCJEzCJEzCJEzCJEzCJEzCJEzCJEzCJEzCJGzwgTWfzR+QMAmTMAmTMAmTMAmTMAmTMAmTMAmTMAmTMAmTMAkbaz6bw677HRy25rM5TMIkTMIkTMIkTMIkTMIkTMIkTMIkTMIkTMIkTMIk7Ae3hw78IVCiuQAAAABJRU5ErkJggg==",
  },
  black: {
    "logo.png":
      "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAQUlEQVR4AbXBwQ3AQAjAsJD9d6YTcI9KsYe35TYcJCABCUhAAhIY3pYfJCABCUhAAhIYYLkNt+UgAQlIQAISkMAHUYgEJoU6Q4AAAAAASUVORK5CYII=",
    "logo@2x.png":
      "iVBORw0KGgoAAAANSUhEUgAAACoAAAAqCAYAAADFw8lbAAAAY0lEQVR4AdXBQQ3AQBDEsGz4c75ymEel2MfusTkGEiEREiEREiEREiEREiEREiEREnHsHj+SCImQCImQCImQCImQCImQCImQiAMem2PzGEiEREiEREiEREiEREiEREiEREjEBzcGBFCUNHrtAAAAAElFTkSuQmCC",
    "logo@3x.png":
      "iVBORw0KGgoAAAANSUhEUgAAAD8AAAA/CAYAAABXXxDfAAAAhElEQVR4AeXBwRHAMAjAMOP9d6ZLkEfP0vDGcm84JmESJmESJmESJmESJmESJmESJmESJmESJmESJmESNryx/ICESZiESZiESZiESZiESZiESZiESZiESZiESZiESdgAy73h3nJMwiRMwiRMwiRMwiRMwiRMwiRMwiRMwiRMwiRMwiTsAwTnBHrCCR73AAAAAElFTkSuQmCC",
  },
};
