name: Send Reminder Emails

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://events.purduehackers.com/api/sendReminder
          CONFIGURATION: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.API_TOKEN }}"} }'
